/**
 * @overview A module to catch and log errors into a file.
 * @author Blocknomic Technologies
 * @license https://desktop.github.com/eula/
 * @version 0.6.9
 */
/**
 * A wrapper class for error logging functions.
 * @module LogHelper
 */
class LogHelper {

    /**
     * Creates an instance of LogHelper.
     * @memberof LogHelper
     */
    constructor() {
        process.on("uncaughtException", this.logUncaughtErrors);
        process.on("unhandledRejection", this.logUncaughtErrors);
    }

    /**
     * A function to log errors generated by a controller to a file.
     * @param {string} controllerThis - Controller
     * @param {string} error - Error
     * @memberof LogHelper
     */
    logErrorFromController(controllerThis, error) {
        let errLogObj = {
            type: 'controller',
            data: {
                when: (new Date().toISOString()),
                user: controllerThis.user,
                uri: controllerThis.uri,
                body: controllerThis.body,
                controller: controllerThis.name,
                headers: controllerThis.headers,
                ip: controllerThis.ip,
                error: {
                    code: error.code,
                    name: error.name,
                    message: error.message,
                    stack: error.stack,
                }
            }
        };
        // F.workers.logger.send(errLogObj);
    }

    /**
     * Afunctino to log uncaught errors to a file.
     * @param {string} error - Uncaught errors
     * @memberof LogHelper
     */
    logUncaughtErrors(error) {
        console.log(error);
        let errLogObj = {
            type: 'uncaught',
            data: {
                when: (new Date().toISOString()),
                error: {
                    code: error.code,
                    name: error.name,
                    message: error.message,
                    stack: error.stack,
                }
            }
        };
        // F.workers.logger.send(errLogObj);
    }
}
/**
 * @exports LogHelper
 */
module.exports = new LogHelper();